-- Find the total sales
SELECT SUM(sales) AS total_sales  FROM gold.fact_sales;

-- Find how many items are sold
SELECT SUM(quantity) AS total_quantity FROM gold.fact_sales;

-- Find Average selling price
SELECT AVG(price) AS avg_price FROM gold.fact_sales;

-- Find the total number of orders
SELECT COUNT(DISTINCT(order_number)) AS orders FROM gold.fact_sales;

-- Find the total number of products
SELECT COUNT(product_name) AS total_producrs FROM gold.dim_products;

-- Find the total number of customers
SELECT COUNT(customer_key) AS total_customers FROM gold.dim_customers;

-- Find the total number of customers that has placed an order
SELECT COUNT(DISTINCT order_date) AS placed_orders FROM gold.fact_sales;



SELECT 'Total sales' as measure_name, SUM(sales) AS measure_value  FROM gold.fact_sales
union all

SELECT 'Total quantity' as measure_name, SUM(quantity) AS measure_value  FROM gold.fact_sales
union all

SELECT 'Avg price' as measure_name, AVG(price) AS measure_value  FROM gold.fact_sales
union all 

SELECT 'Total num orders' as measure_name, COUNT(DISTINCT order_number) AS measure_value  FROM gold.fact_sales
union all

SELECT 'Total num products' as measure_name, COUNT(product_name) AS measure_value  FROM gold.dim_products
union all

SELECT 'Total num customers' as measure_name, COUNT(customer_key) AS measure_value  FROM gold.dim_customers
union all

SELECT 'Total orders placed' as measure_name, COUNT(DISTINCT order_date) AS measure_value  FROM gold.fact_sales





-- Find total customers by countries

SELECT
	country,
	COUNT(customer_key) AS total_customers
FROM gold.dim_customers
GROUP BY country
ORDER BY total_customers DESC;


-- Find the total customers by gender

SELECT 
	gender,
	COUNT(customer_key) AS total_customers_by_gender
FROM gold.dim_customers
GROUP BY gender 
ORDER BY total_customers_by_gender DESC;


-- Find total products by category

SELECT 
	category,
	COUNT(product_id) AS total_products
FROM gold.dim_products
GROUP BY category
ORDER BY total_products DESC;


-- What is the average costs in each category?

SELECT
	category,
	AVG(cost) AS avg_cost
FROM gold.dim_products
GROUP BY category 
ORDER BY avg_cost DESC;


-- What is the total revenue generated for each category?


SELECT
	p.category,
	SUM(f.sales) AS total_revenue
FROM gold.fact_sales f
LEFT JOIN gold.dim_products p
ON p.product_key = f.product_key
GROUP BY p.category 
ORDER BY total_revenue DESC;


-- Find total revenue is generated by each customer

SELECT 
	c.customer_key,
	c.first_name,
	c.last_name,
	SUM(f.sales) AS total_revenue
FROM gold.fact_sales f
LEFT JOIN gold.dim_customers c
ON c.customer_key = f.customer_key
GROUP BY 
	c.customer_key,
	c.first_name,
	c.last_name
ORDER BY total_revenue DESC;


-- What is the distribution of sold items across the countries

SELECT 
	c.country,
	SUM(f.quantity) AS total_sold_items
FROM gold.fact_sales f
LEFT JOIN gold.dim_customers c
ON c.customer_key = f.customer_key
GROUP BY 
	c.country
ORDER BY total_sold_items DESC;


-- Which 5 products generate highest revenue

SELECT TOP 5
	p.product_name,
	SUM(f.sales) AS total_revenue
FROM gold.fact_sales f
LEFT JOIN gold.dim_products p
ON p.product_key = f.product_key
GROUP BY p.product_name 
ORDER BY total_revenue DESC;


-- What are the 5 worst performing products in terms of sales

SELECT TOP 5
	p.product_name,
	SUM(f.sales) AS total_revenue
FROM gold.fact_sales f
LEFT JOIN gold.dim_products p
ON p.product_key = f.product_key
GROUP BY p.product_name 
ORDER BY total_revenue;


SELECT * FROM(
SELECT 
	p.product_name,
	SUM(f.sales) AS total_revenue,
	ROW_NUMBER() over(order by SUM(f.sales) DESC ) As rank_pr
FROM gold.fact_sales f
LEFT JOIN gold.dim_products p
ON p.product_key = f.product_key
GROUP BY p.product_name ) t
WHERE rank_pr <= 5;
